# master branch
# compile, test, release to nuget
-
  branches:
    only:
    - master

  version: 1.0.{build}

  init:
  - ps: |
      $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
      $env:PackageVersion = "{0}.{1}.{2}" -f $version.Major, $version.Minor, $version.Build

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_file_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_informational_version: '$(APPVEYOR_BUILD_VERSION)'

  configuration: Release

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true

  before_build:
  - nuget restore

  build:
    verbosity: minimal

  after_build:
  - ps: nuget pack FluentAdb/FluentAdb.nuspec -version "$env:PackageVersion"

  artifacts:
  - path: 'FluentAdb*.nupkg'
    name: fluentadb-nuget-package

  deploy:
  - provider: NuGet
    api_key:
      secure: xk84qh7+ERRhQigMeqULW/Wnx7lLtMtrsQ2M3/HXPz4=
    artifact: fluentadb-nuget-package

  # notifications:
  # - provider: Webhook
  #   url: https://webhooks.gitter.im/e/3712526962bd70e49d63
  #   on_build_failure: true
  #   on_build_success: true
  #   on_build_status_changed: true