# master branch
# compile, test, release to nuget
-
  branches:
    only:
    - master

  version: 1.0.{build}

  init:
  - ps: |
      $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
      $env:PackageVersion = "{0}.{1}.{2}" -f $version.Major, $version.Minor, $version.Build

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_file_version: '$(APPVEYOR_BUILD_VERSION)'
    assembly_informational_version: '$(APPVEYOR_BUILD_VERSION)'

  configuration: Release

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true

  before_build:
  - nuget restore

  build:
    verbosity: minimal
    publish_nuget: true

  after_build:
  - ps: nuget pack FluentAdb/FluentAdb.csproj.nuspec -version "$env:PackageVersion"

  after_test:
  - bash <(curl -s https://codecov.io/bash)

  artifacts:
  - path: '**\FluentAdb*.nupkg'
    name: fluentadb-nuget-package

  deploy:
  - provider: NuGet
    api_key:
      secure: Q2MFsjBTRxzvwmcXs9s850JeRJFORfGuBcmDh9RUAMDYDxTOODahB0kVkX4p04xo
    artifact: fluentadb-nuget-package
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true 

  - provider: GitHub
    api_key:
      secure: R1G4RaSGXWdhWx85IcLSECRh5D9pt61oTJM2gV1ep3KLO3PWi3GXrshlPjsFkefV
    artifact: /.**\FluentAdb*.nupkg/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only

  # notifications:
  # - provider: Webhook
  #   url: https://webhooks.gitter.im/e/3712526962bd70e49d63
  #   on_build_failure: true
  #   on_build_success: true
  #   on_build_status_changed: true